Lexikar/Controllers/4EUPLUS/UPLOAD_4EUPLUSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lexikar.DAL;
using Lexikar.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Lexikar.Controllers._4EUPLUS
{
    [Route("4EUPLUS-LEX")]
    public class UPLOAD_4EUPLUSController : UploadController
    {
        public UPLOAD_4EUPLUSController(DictionaryContext context, IOptions<LoginDetailModel> app) : base (context, app)
        {
            CloneID = 1; // See TranslationController constructor comments.
        }
    }
}

Lexikar/Views/UPLOAD_4EUPLUS/Delete.cshtml
@model Lexikar.Models.CorpusFile

@{
    ViewData["Title"] = "Delete";
}

    <div class="well well-lg" style="background-color: white">
        <h1>Delete</h1>

        <div style="display:none" id="loginfail" class="alert alert-danger alert-dismissible" role="alert">
            You are not logged in! <a href="/legilex-fr/Login">LOGIN</a>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>CorpusFile</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="ID" />
                <input type="hidden" class="pass" name="Pass" value="" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a asp-action="Index">Back to List</a>
            </form>
        </div>
    </div>
    <script>
         // Do not store passwords like this, use tonkes.

    function getCookie(cname) {
        var name = cname + "=";
        var decodedCookie = decodeURIComponent(document.cookie);
        var ca = decodedCookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }
        }
        return "";
    }

    function checkCookie() {
        var secret = getCookie("secret");
        if (secret != "") {
            var elements = document.getElementsByClassName("pass");
            l = elements.length;
            for (i = 0; i < l; i++) {
                elements[i].value = secret;
            }
        }
        else {
            document.getElementById("loginfail").style.display = "block";
        }
    }

    window.onload = checkCookie;
    </script>

Lexikar/Views/UPLOAD_4EUPLUS/Index.cshtml
@model IEnumerable<Lexikar.Models.CorpusFile>
@{
    ViewBag.Title = "File upload";
}
<style>
    #btnSubmit {
        float: right;
    }

    .well, .container {
        overflow: hidden;
    }

    .container, .row, .row > div, .col-sm-6 {
        height: inherit;
    }

    .col-sm-6, .well-lg {
        display: flex;
        flex-direction: column;
    }

    .col-sm-6 {
        flex: 1;
    }

    .forms, .files {
        flex: 1;
        padding-left: 5px;
        padding-right: 5px;
        overflow-y: scroll;
        overflow-x: hidden;
    }

    .headerbox {
        display: flex;
    }

    .headerbox > h2 {
        flex: 1;
        text-align: center;
    }
</style>
<div class="container">
    <div class="row well well-lg" style="background-color: lightgray">
        <div>
            <div style="display:none" id="loginfail" class="alert alert-danger alert-dismissible" role="alert">
                You are not logged in! <a href="/legilex-fr/Login">LOGIN</a>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @if (ViewBag.CorpusErrorConflictingNames != null && ViewBag.CorpusErrorConflictingNames.Count > 0)
            {
                <style>
                    .alert-danger ol, .alert-danger li {
                        display: inline-block;
                    }
                </style>
                <div class="alert alert-danger alert-dismissible" role="alert">
                    There are already corpus files in the database with the same name:
                    <ol>
                        @foreach (var item in ViewBag.CorpusErrorConflictingNames)
                        {
                            <li>@item</li>
                        }
                    </ol>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
            @if (!String.IsNullOrEmpty(ViewBag.Error))
            {
                <div class="alert alert-danger alert-dismissible" role="alert">
                    @ViewBag.Error
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
            @if (!String.IsNullOrEmpty(ViewBag.Message))
            {
                <div class="alert alert-success alert-dismissible" role="alert">
                    @ViewBag.Message
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
            <div class="col-sm-6">
                <div class="well well-sm headerbox">
                    <h2>File upload</h2>
                </div>
                <div class="forms well">
                    <div class="well">
                        <h3>Termbase</h3>
                        <h4>@ViewBag.Message</h4>
                        @using (Html.BeginForm("FileUploadLex", "UPLOAD_4EUPLUS", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {

                            <ol>
                                <li class="lifile">
                                    <input type="file" id="fileToUpload" name="Lex" />
                                    <span class="field-validation-error" id="spanfile"></span>
                                </li>
                            </ol>
                            <input type="hidden" class="pass" value="" name="Pass" />
                            <input type="submit" id="btnSubmit" value="Upload" />
                        }
                    </div>

                    <div class="well">
                        <h3>Corpus</h3>
                        @using (Html.BeginForm("FileUploadCorpus", "UPLOAD_4EUPLUS", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <ol>
                                <li class="lifile">
                                    <input type="file" id="fileToUpload" name="Corpus" multiple />
                                    <span class="field-validation-error" id="spanfile"></span>
                                </li>
                            </ol>
                            <span>Hold Ctrl to select more than one file.</span>
                            <input type="hidden" class="pass" value="" name="Pass" />
                            <input type="submit" id="btnSubmit" value="Upload" />
                        }
                    </div>

                    <div class="well">
                        <h3>About</h3>
                        @using (Html.BeginForm("FileUploadAbout", "UPLOAD_4EUPLUS", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <ol>
                                <li class="lifile">
                                    <input type="file" id="fileToUpload" name="About" />
                                    <span class="field-validation-error" id="spanfile"></span>
                                </li>
                            </ol>
                            <input type="hidden" class="pass" value="" name="Pass" />
                            <input type="submit" id="btnSubmit" value="Upload" />
                        }
                    </div>

                    <div class="well">
                        <h3>Help</h3>
                        @using (Html.BeginForm("FileUploadHelp", "UPLOAD_4EUPLUS", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <ol>
                                <li class="lifile">
                                    <input type="file" id="fileToUpload" name="Help" />
                                    <span class="field-validation-error" id="spanfile"></span>
                                </li>
                            </ol>
                            <input type="hidden" class="pass" value="" name="Pass" />
                            <input type="submit" id="btnSubmit" value="Upload" />
                        }
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="well well-sm headerbox">
                    <h2>Corpus files</h2>
                </div>
                <div class="files well" style="flex: 1">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @*<a asp-action="Details" asp-route-id="@item.ID">Details</a> |*@
                                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>

    <script type="text/jscript">    // Duplicite script. Put in separate file.
        //get file size
        function GetFileSize(file) {
            try {
                var fileSize = 0;
                fileSize = file[0].files[0].size //size in kb
                fileSize = fileSize / 1048576; //size in mb
                return fileSize;
            }
            catch (e) {
                alert("Error is :" + e);
            }
        }

        //get file path from client system
        function getNameFromPath(strFilepath) {
            var objRE = new RegExp(/([^\/\\]+)$/);
            var strName = objRE.exec(strFilepath);

            if (strName == null) {
                return null;
            }
            else {
                return strName[0];
            }
        }

        $("form").on("click", "#btnSubmit", function () {
            if ($(this).closest("form").find('#fileToUpload').val() == "") {
                $(this).closest("form").find("#spanfile").html("Please upload file");
                return false;
            }
            else {
                return checkfile($(this).closest("form").find('#fileToUpload'));
            }
        });

        function checkfile(changedEl) {
            var file = $(changedEl).val();
            if (file != null) {
                var extension = file.substr((file.lastIndexOf('.') + 1));

                if ($(changedEl).attr("name") === "Lex" && extension !== "csv") {
                    $(changedEl).closest("form").find("#spanfile").text("You can upload only csv extension file");
                    return false;
                }
                else if ($(changedEl).attr("name") === "Lex" && extension === "csv") {
                    flag = true;
                }
                else if (extension !== "txt") {
                    $(changedEl).closest("form").find("#spanfile").text("You can upload only txt extension file");
                    return false;
                }
                else if (extension === "txt") {
                    flag = true;
                }
                if (flag) {
                    var size = GetFileSize($(changedEl).closest("form").find('#fileToUpload'));
                    if (size > 30) {
                        $(changedEl).closest("form").find("#spanfile").text("You can upload file up to 30 MB");
                        return false;
                    }
                    else {
                        $(changedEl).closest("form").find("#spanfile").text("");
                    }
                }
            }
        }

        $(function () {
            $("[id=fileToUpload]").change(function () {
                checkfile(this);
            });
        });


        function getCookie(cname) {
            var name = cname + "=";
            var decodedCookie = decodeURIComponent(document.cookie);
            var ca = decodedCookie.split(';');
            for (var i = 0; i < ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0) == ' ') {
                    c = c.substring(1);
                }
                if (c.indexOf(name) == 0) {
                    return c.substring(name.length, c.length);
                }
            }
            return "";
        }

        function checkCookie() {
            var secret = getCookie("secret");
            if (secret != "") {
                var elements = document.getElementsByClassName("pass");
                l = elements.length;
                for (i = 0; i < l; i++) {
                    elements[i].value = secret;
                }
            }
            else {
                document.getElementById("loginfail").style.display = "block";
            }
        }

        window.onload = checkCookie;

    </script>

Lexikar/Views/UPLOAD_4EUPLUS/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<div class="container">
    <div class="row well well-lg" style="background-color: lightgray">
        <div class="well">
            <div style="display:none">
                <div id ="messageLogout" class="alert alert-success alert-dismissible" role="alert">
                    You logged out!
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <div id="displayMessage">
                @if (!String.IsNullOrEmpty(ViewBag.Error))
                {
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        @ViewBag.Error
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
            </div>
            <div id="login">
                @using (Html.BeginForm("Login", "UPLOAD_4EUPLUS", FormMethod.Post, new { style = "width: 50%;", id = "login" }))
                {
                    <h3>Login:</h3>
                    <input type="password" name="password" placeholder="Password" id="pass" style="background-color: white; width: 60%;" />
                    <button type="submit" value="Login" style="width: 20%;">Login</button>
                }
                <hr />
            </div>
            <div id="logout" style="display:none">
                <button id="btnLogout" onclick="logout()">Log out</button>
            </div>
        </div>
    </div>
</div>

<script> // Duplicite script. Put in separate file.

    // Do not store passwords like this!

    function logout() {
        document.cookie = "secret= ; expires = Thu, 01 Jan 1970 00:00:00 GMT ; path=/"
        var elmnt = document.getElementById("messageLogout");
        var cln = elmnt.cloneNode(true);
        cln.id = "msg";
        document.getElementById("displayMessage").appendChild(cln);
        document.getElementById("login").style.display = "block";
        document.getElementById("logout").style.display = "none";
    }

    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        var expires = "expires=" + d.toGMTString();
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }

    function getCookie(cname) {
        var name = cname + "=";
        var decodedCookie = decodeURIComponent(document.cookie);
        var ca = decodedCookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }
        }
        return "";
    }

    function checkCookie()
    {
        var secret = getCookie("secret");
        if (secret != "")
        {
            document.getElementById("login").style.display = "none";
            document.getElementById("logout").style.display = "block";
        }
    }
    
    window.onload = checkCookie;
</script>

Lexikar/Views/UPLOAD_4EUPLUS/LoginConfirmed.cshtml
@{
    ViewBag.Title = "Login";
}
<div class="container">
    <div class="row well well-lg" style="background-color: lightgray">
        <div class="well">
            @if (!String.IsNullOrEmpty(ViewBag.Error))
            {
                <div class="alert alert-danger alert-dismissible" role="alert">
                    @ViewBag.Error
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <a href="/4EUPLUS-LEX/Login">Back to login page</a>
            }
            @if (!String.IsNullOrEmpty(ViewBag.Message))
            {
                <div class="alert alert-success alert-dismissible" role="alert">
                    @ViewBag.Message
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div style="display:none" id="secret">@ViewBag.Secret</div>
                <a href="/4EUPLUS-LEX/Upload">Continue to administration</a>
            }
        </div>
    </div>
</div>

<script> // Duplicite script. Put in separate file.
    // Do not store passwords like this!
    function loadSecret() {
        var x = document.getElementById("secret").textContent;  // Use descriptive variable names, not 'x'.
        setCookie("secret", x, 1);
    }
    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        var expires = "expires=" + d.toGMTString();
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }
    window.onload = loadSecret;
</script>