Lexikar/Controllers/4EUPLUS/4EUPLUSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lexikar.DAL;
using Microsoft.AspNetCore.Mvc;

namespace Lexikar.Controllers
{

    [Route("4EUPLUS-LEX")]
    public class _4EUPLUSController : TranslationController
    {
        public _4EUPLUSController(DictionaryContext context) : base(context)
        {
            CloneID = 1; // See TranslationController constructor comments.
        }
    }
}

Lexikar/Controllers/4EUPLUS/UPLOAD_4EUPLUSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lexikar.DAL;
using Lexikar.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Lexikar.Controllers._4EUPLUS
{
    [Route("4EUPLUS-LEX")]
    public class UPLOAD_4EUPLUSController : UploadController
    {
        public UPLOAD_4EUPLUSController(DictionaryContext context, IOptions<LoginDetailModel> app) : base (context, app)
        {
            CloneID = 1; // See TranslationController constructor comments.
        }
    }
}

Lexikar/Views/_4EUPLUS/About.cshtml
<div class="well well-lg">
    <h2>About</h2>
    <pre style="white-space: pre-wrap; font-family: Verdana; font-size: 15px;">
        @if (Model != null)
        {
            @Model.text
        }
    </pre>
</div>

Lexikar/Views/_4EUPLUS/Help.cshtml
<div class="well well-lg">
    <h2>Help</h2>
    <pre style="white-space: pre-wrap; font-family: Verdana; font-size: 15px;">
        @if (Model != null)
        {
            @Model.text
        }
    </pre>
</div>

Lexikar/Views/_4EUPLUS/__4EUPLUSLayout.cshtml
<!DOCTYPE html>
<html style="height:100%">
<head>
    <meta name="author" content="Petr Beneš">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    @*<link rel="stylesheet" href="/css/site.css" type="text/css" />*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>4EU+LEX</title>
</head>
<body style="    height: 100%;
        background: rgb(9,9,121);
        background: linear-gradient(0deg, rgba(9,121,9,1) 10%, rgba(65,200,109,1) 80%, rgba(105,255,200,1) 100%);
        background-repeat: no-repeat;
        background-attachment: fixed;
        padding-bottom: 0;
        display: flex;
        flex-direction: column;
    ">
    <div class="navbar-fixed-top navbar" style="background-color: green; ">
        <style scoped>
            .wainb a {
                color: white;
            }
            .bwh a:focus:hover, .bwh a:hover {
                color: black;
                font-weight: bold;
            }
        </style>
        <div class="container wainb">
            <div class="navbar-header">
                @Html.ActionLink("4EU+LEX", "Index", "_4EUPLUS", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse bwh">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "_4EUPLUS")</li>
                    <li>@Html.ActionLink("About", "About", "_4EUPLUS")</li>
                    <li>@Html.ActionLink("Help", "Help", "_4EUPLUS")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="height:100%; padding-left: 15px; padding-right: 15px; padding-top:50px">
        <div style="height: 100%;">
            @RenderBody()
        </div>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>