Lexikar/Controllers/Translation/TranslationController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Lexikar.DAL;
using Lexikar.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Lexikar.Controllers
{
    public class SearchResults // Move to separate file
    {
        public List<Translation> FR { get; set; } = new List<Translation>(); // Other languages are used as well
        public List<Translation> CS { get; set; } = new List<Translation>();
        public List<CorpusString> Corpus { get; set; } = new List<CorpusString>();
        public class CorpusString
        {
            public int rownumber;
            public string left = "";
            public string right = "";
            public string middle = "";
            public string left_middle = "";
            public string right_middle = "";
            public string source = "";
        }
    }
    [Route("legilex-fr")]
    public class TranslationController : Controller
    {
        protected readonly DictionaryContext _context;

        protected int CloneID;
        public TranslationController(DictionaryContext context)
        {
            _context = context;
            CloneID = 0;    // Add another level of abstraction,
                            // specify CloneID only for concrete classes
                            // instead of overwriting it in child constructors.
        }


        // GET: Translation
        [Route("")]
        [Route("Index")]
        [Route("Index/{id?}/{searchString?}/{sortchoice?}/{orderby?}")]
        public async Task<ActionResult> Index(string searchString, string sortChoice, string orderBy, int? id = 0)
        {
            ViewBag.ID = id;
            SearchResults results = new SearchResults();

            ListFilter(searchString, results);
            CorpusRoutine(searchString, results);
            SortRoutine(sortChoice, orderBy, results);
            
            // Use paging / split into different methods and call with Ajax instead of returning whole database
            return View(model: results);

            // local functions;

            // These functions should be in a repository
            // Use returned value instead of relying on the metod to edit content of the imput parameter results
            void ListFilter(string searchString, SearchResults results)
            {
                ViewBag.SearchString = searchString == null ? "" : searchString;

                // Misterious uncomented regex. What does it do? Use decriptive names
                const string pattern = "\\([^)]*?\\)";

                if (String.IsNullOrEmpty(searchString))
                {
                    // Change to query database and not localy
                    results.FR = _context.Translations.Where(x => x.CloneID == this.CloneID).ToList();                    
                    results.FR = results.FR.OrderBy(t =>
                    {
                        
                        return Regex.Replace(t.FR, pattern, "");
                    }).ToList();

                    // Change to query database and not localy
                    results.CS = _context.Translations.Where(x => x.CloneID == this.CloneID).ToList();
                    results.CS = results.CS.OrderBy(t => Regex.Replace(t.CS, pattern, "")).ToList(); 
                }
                else
                {
                    // Change to query database and not localy
                    results.FR = _context.Translations.Where(x => x.CloneID == this.CloneID).ToList();
                    //results.FR = results.FR.Where(t => Regex.Replace(t.FR, "\\([^)]*?\\)", "").Contains(searchString)).OrderBy(t => Regex.Replace(t.FR, "\\([^)]*?\\)", "")).ToList();

                    // Returns list of results in FR column regardless of case.
                    results.FR = results.FR
                        .Where
                        (
                            t =>
                            CultureInfo.InvariantCulture.CompareInfo
                            .IndexOf
                            (
                                Regex.Replace(t.FR, pattern, ""),    
                                searchString,
                                CompareOptions.IgnoreCase
                            ) >= 0
                        )
                        .OrderBy
                        (
                            t => 
                            Regex.Replace(t.FR, pattern, "") 
                        )
                        .ToList();

                    // Change to query database and not localy
                    results.CS = _context.Translations.Where(x => x.CloneID == this.CloneID).ToList();
                    results.CS = results.CS
                        .Where
                        (
                            t =>
                            CultureInfo.InvariantCulture.CompareInfo
                            .IndexOf(
                                Regex.Replace(t.CS, pattern, ""), 
                                searchString,
                                CompareOptions.IgnoreCase) >= 0
                        )
                        .OrderBy
                        (
                            t =>
                            Regex.Replace(t.CS, pattern, "") 
                        ) 
                        .ToList();

                    // Clean up commented code

                    //results.FR = _context.Translations.Where(t => t.FR.Contains(searchString)).OrderBy(t => t.FR).ToList();
                    //results.CS = _context.Translations.Where(t => t.CS.Contains(searchString)).OrderBy(t => t.CS).ToList();
                }
                foreach (var item in results.FR)
                {
                    item.FR = item.FR.Replace("(", "<mark class=\"lexitem\">(").Replace(")", ")</mark>");
                }
                foreach (var item in results.CS)
                {
                    item.CS = item.CS.Replace("(", "<mark class=\"lexitem\">(").Replace(")", ")</mark>");
                }
            }
            void CorpusRoutine(string searchString, SearchResults results)
            {
                if (String.IsNullOrEmpty(searchString))
                    return;
                char[] spacers = { ' ' /*space*/, '.', ',', '!', '?', ':', '(', ')', ' ' /*nbsp*/ };

                // Change to query database and not localy
                var list = _context.CorpusSources
                    .Include(c => c.CorpusFile)
                    .Where(c => c.CloneID == this.CloneID)
                    .ToList()
                    .Where(c => c.TextRow.Contains(searchString, StringComparison.OrdinalIgnoreCase));

                foreach (var item in list)
                {
                    int index = item.TextRow.IndexOf(ViewBag.SearchString, StringComparison.OrdinalIgnoreCase);
                    int start = item.TextRow.LastIndexOfAny(spacers, index);
                    // Full names, not abbreviations
                    int startOfLeftMiddleWord = -1;
                    int endOfRightMiddleWord = -1; 
                    if (start <= 0)
                        start = 0;   // v případě žádného předcházejího spaceru je slovo na začátku
                    else
                    {
                        startOfLeftMiddleWord = item.TextRow.LastIndexOfAny(spacers, start - 1);
                        if (startOfLeftMiddleWord < 0)
                            startOfLeftMiddleWord = 0;
                    }
                    int end = item.TextRow.Length;
                    int count = item.TextRow.IndexOfAny(spacers, index + searchString.Length, end - (index + searchString.Length)) - start;
                    if (count < 0)
                    {
                        count = end - start; // v případě žádného následujícího spaceru je slovo na konci
                        endOfRightMiddleWord = start + count;
                    }
                    else
                    {
                        endOfRightMiddleWord = item.TextRow.IndexOfAny(spacers, start + count + 1, end - (start + count + 1));
                        if (endOfRightMiddleWord < 0)
                            //ermw = start + count;
                            endOfRightMiddleWord = end;
                    }
                    int rownumber = item.RowNumber;
                    string left = startOfLeftMiddleWord > -1 
                        ? item.TextRow.Substring(0, startOfLeftMiddleWord + 1) 
                        : item.TextRow.Substring(0, start);
                    left = left.Trim(' '/*nbsp*/, ' '/*space*/);
                    string left_middle = startOfLeftMiddleWord > -1 ? item.TextRow.Substring(startOfLeftMiddleWord, start - startOfLeftMiddleWord) : "";
                    string middle = item.TextRow.Substring(start, count);
                    string right_middle = item.TextRow.Substring(start + count, endOfRightMiddleWord - start - count);
                    string right = item.TextRow.Substring(endOfRightMiddleWord, end - endOfRightMiddleWord);

                    if (middle[0] == '(')
                    {
                        middle = middle.Trim('(');
                        left_middle = left_middle + "(";
                    }
                    if (left_middle.Length == 1 && left.Length >= 1 && left[left.Length - 1] == left_middle[0])
                    {
                        left_middle = "";
                    }

                    results.Corpus.Add(new SearchResults.CorpusString()
                    {
                        rownumber = rownumber,
                        left = left,
                        left_middle = left_middle,
                        middle = middle,
                        right_middle = right_middle,

Lexikar/Views/Deprecated/FileUpload.cshtml
@{
    ViewBag.Title = "Nahrávání souboru";
}
    <div style="background-color:lightgoldenrodyellow">
        <h2>FileUpload</h2>
        <h3>@ViewBag.Message</h3>
        @using (Html.BeginForm("FileUpload", "Translation", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary();
            <ol>
                <li class="lifile">
                    <input type="file" id="fileToUpload" name="file" />
                    <span class="field-validation-error" id="spanfile"></span>
                </li>
            </ol>
            <input type="submit" id="btnSubmit" value="Upload" />
        }
        <hr />
        @Html.ActionLink("Database | ", "FileUpload")
        @Html.ActionLink("About | ", "FileUploadAbout")
        @Html.ActionLink("Help", "FileUploadHelp")
        @Html.ActionLink("Corpus", "FileUploadCorpus")
    </div>

<script type="text/jscript">
    //get file size
    function GetFileSize(fileid) {
        try {
            var fileSize = 0;
            //for IE
            if ($.browser.msie) {
                //before making an object of ActiveXObject,
                //please make sure ActiveX is enabled in your IE browser
                var objFSO = new ActiveXObject("Scripting.FileSystemObject"); var filePath = $("#" + fileid)[0].value;
                var objFile = objFSO.getFile(filePath);
                var fileSize = objFile.size; //size in kb
                fileSize = fileSize / 1048576; //size in mb
            }
            //for FF, Safari, Opeara and Others
            else {
                fileSize = $("#" + fileid)[0].files[0].size //size in kb
                fileSize = fileSize / 1048576; //size in mb
            }
            return fileSize;
        }
        catch (e) {
            alert("Error is :" + e);
        }
    }

    //get file path from client system
    function getNameFromPath(strFilepath) {
        var objRE = new RegExp(/([^\/\\]+)$/);
        var strName = objRE.exec(strFilepath);

        if (strName == null) {
            return null;
        }
        else {
            return strName[0];
        }
    }

    $("#btnSubmit").live("click", function () {
        if ($('#fileToUpload').val() == "") {
            $("#spanfile").html("Please upload file");
            return false;
        }
        else {
            return checkfile();
        }
    });

    function checkfile() {
        var file = getNameFromPath($("#fileToUpload").val());
        if (file != null) {
            var extension = file.substr((file.lastIndexOf('.') + 1));
            // alert(extension);
            switch (extension) {
                case 'csv':
                    flag = true;
                    break;
                default:
                    flag = false;
            }
        }
        if (flag == false) {
            $("#spanfile").text("You can upload only csv extension file");
            return false;
        }
        else {
            var size = GetFileSize('fileToUpload');
            if (size > 3) {
                $("#spanfile").text("You can upload file up to 3 MB");
                return false;
            }
            else {
                $("#spanfile").text("");
            }
        }
    }

    $(function () {
        $("#fileToUpload").change(function () {
            checkfile();
        });
    });
</script>

Lexikar/Views/Deprecated/FileUploadAbout.cshtml
@{
    ViewBag.Title = "ABOUT - Nahrávání souboru";
}
    <div style="background-color:lightgoldenrodyellow">
        <h2>ABOUT - FileUpload</h2>
        <h3>@ViewBag.Message</h3>
        @using (Html.BeginForm("FileUploadAbout", "Translation", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary();
            <ol>
                <li class="lifile">
                    <input type="file" id="fileToUpload" name="file" />
                    <span class="field-validation-error" id="spanfile"></span>
                </li>
            </ol>
            <input type="submit" id="btnSubmit" value="Upload" />
        }
        <hr />
        @Html.ActionLink("Database | ", "FileUpload")
        @Html.ActionLink("About | ", "FileUploadAbout")
        @Html.ActionLink("Help", "FileUploadHelp")
        @Html.ActionLink("Corpus", "FileUploadCorpus")
    </div>

        <script type="text/jscript">
            //get file size
            function GetFileSize(fileid) {
                try {
                    var fileSize = 0;
                    //for IE
                    if ($.browser.msie) {
                        //before making an object of ActiveXObject,
                        //please make sure ActiveX is enabled in your IE browser
                        var objFSO = new ActiveXObject("Scripting.FileSystemObject"); var filePath = $("#" + fileid)[0].value;
                        var objFile = objFSO.getFile(filePath);
                        var fileSize = objFile.size; //size in kb
                        fileSize = fileSize / 1048576; //size in mb
                    }
                    //for FF, Safari, Opeara and Others
                    else {
                        fileSize = $("#" + fileid)[0].files[0].size //size in kb
                        fileSize = fileSize / 1048576; //size in mb
                    }
                    return fileSize;
                }
                catch (e) {
                    alert("Error is :" + e);
                }
            }

            //get file path from client system
            function getNameFromPath(strFilepath) {
                var objRE = new RegExp(/([^\/\\]+)$/);
                var strName = objRE.exec(strFilepath);

                if (strName == null) {
                    return null;
                }
                else {
                    return strName[0];
                }
            }

            $("#btnSubmit").live("click", function () {
                if ($('#fileToUpload').val() == "") {
                    $("#spanfile").html("Please upload file");
                    return false;
                }
                else {
                    return checkfile();
                }
            });


            
            function checkfile() {
                var file = getNameFromPath($("#fileToUpload").val());
                if (file != null) {
                    var extension = file.substr((file.lastIndexOf('.') + 1));
                    // alert(extension);
                    switch (extension) {
                        case 'txt':
                            flag = true;
                            break;
                        default:
                            flag = false;
                    }
                }
                if (flag == false) {
                    $("#spanfile").text("You can upload only txt extension file");
                    return false;
                }
                else {
                    var size = GetFileSize('fileToUpload');
                    if (size > 3) {
                        $("#spanfile").text("You can upload file up to 3 MB");
                        return false;
                    }
                    else {
                        $("#spanfile").text("");
                    }
                }
            }

            $(function () {
                $("#fileToUpload").change(function () {
                    checkfile();
                });
            });
        </script>

Lexikar/Views/Deprecated/FileUploadCorpus.cshtml
@{
    ViewBag.Title = "Korpus - Nahrávání souboru";
}
    <div style="background-color:lightgoldenrodyellow">
        <h2>Korpus - FileUpload</h2>
        <h3>@ViewBag.Message</h3>
        @using (Html.BeginForm("FileUploadCorpus", "Translation", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary();
            <ol>
                <li class="lifile">
                    <input type="file" id="fileToUpload" name="file" />
                    <span class="field-validation-error" id="spanfile"></span>
                </li>
            </ol>
            <input type="submit" id="btnSubmit" value="Upload" />
        }
        <hr />
        @Html.ActionLink("Database | ", "FileUpload")
        @Html.ActionLink("About | ", "FileUploadAbout")
        @Html.ActionLink("Help", "FileUploadHelp")
        @Html.ActionLink("Corpus", "FileUploadCorpus")
    </div>

<script type="text/jscript">
    //get file size
    function GetFileSize(fileid) {
        try {
            var fileSize = 0;
            //for IE
            if ($.browser.msie) {
                //before making an object of ActiveXObject,
                //please make sure ActiveX is enabled in your IE browser
                var objFSO = new ActiveXObject("Scripting.FileSystemObject"); var filePath = $("#" + fileid)[0].value;
                var objFile = objFSO.getFile(filePath);
                var fileSize = objFile.size; //size in kb
                fileSize = fileSize / 1048576; //size in mb
            }
            //for FF, Safari, Opeara and Others
            else {
                fileSize = $("#" + fileid)[0].files[0].size //size in kb
                fileSize = fileSize / 1048576; //size in mb
            }
            return fileSize;
        }
        catch (e) {
            alert("Error is :" + e);
        }
    }

    //get file path from client system
    function getNameFromPath(strFilepath) {
        var objRE = new RegExp(/([^\/\\]+)$/);
        var strName = objRE.exec(strFilepath);

        if (strName == null) {
            return null;
        }
        else {
            return strName[0];
        }
    }

    $("#btnSubmit").live("click", function () {
        if ($('#fileToUpload').val() == "") {
            $("#spanfile").html("Please upload file");
            return false;
        }
        else {
            return checkfile();
        }
    });

    // TODO: Checkcs only the first file!
    function checkfile() {
        var file = getNameFromPath($("#fileToUpload").val());
        if (file != null) {
            var extension = file.substr((file.lastIndexOf('.') + 1));
            // alert(extension);
            switch (extension) {
                case 'txt':
                    flag = true;
                    break;
                default:
                    flag = false;
            }
        }
        if (flag == false) {
            $("#spanfile").text("You can upload only txt extension file");
            return false;
        }
        else {
            var size = GetFileSize('fileToUpload');
            if (size > 30) {
                $("#spanfile").text("You can upload file up to 30 MB");
                return false;
            }
            else {
                $("#spanfile").text("");
            }
        }
    }

    $(function () {
        $("#fileToUpload").change(function () {
            checkfile();
        });
    });
</script>

Lexikar/Views/Deprecated/FileUploadHelp.cshtml
@{
    ViewBag.Title = "HELP - Nahrávání souboru";
}
    <div style="background-color:lightgoldenrodyellow">
        <h2>HELP - FileUpload</h2>
        <h3>@ViewBag.Message</h3>
        @using (Html.BeginForm("FileUploadHelp", "Translation", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary();
            <ol>
                <li class="lifile">
                    <input type="file" id="fileToUpload" name="file" />
                    <span class="field-validation-error" id="spanfile"></span>
                </li>
            </ol>
            <input type="submit" id="btnSubmit" value="Upload" />
        }
        <hr />
        @Html.ActionLink("Database | ", "FileUpload")
        @Html.ActionLink("About | ", "FileUploadAbout")
        @Html.ActionLink("Help", "FileUploadHelp")
        @Html.ActionLink("Corpus", "FileUploadCorpus")
    </div>

        <script type="text/jscript">
            //get file size
            function GetFileSize(fileid) {
                try {
                    var fileSize = 0;
                    //for IE
                    if ($.browser.msie) {
                        //before making an object of ActiveXObject,
                        //please make sure ActiveX is enabled in your IE browser
                        var objFSO = new ActiveXObject("Scripting.FileSystemObject"); var filePath = $("#" + fileid)[0].value;
                        var objFile = objFSO.getFile(filePath);
                        var fileSize = objFile.size; //size in kb
                        fileSize = fileSize / 1048576; //size in mb
                    }
                    //for FF, Safari, Opeara and Others
                    else {
                        fileSize = $("#" + fileid)[0].files[0].size //size in kb
                        fileSize = fileSize / 1048576; //size in mb
                    }
                    return fileSize;
                }
                catch (e) {
                    alert("Error is :" + e);
                }
            }

            //get file path from client system
            function getNameFromPath(strFilepath) {
                var objRE = new RegExp(/([^\/\\]+)$/);
                var strName = objRE.exec(strFilepath);

                if (strName == null) {
                    return null;
                }
                else {
                    return strName[0];
                }
            }

            $("#btnSubmit").live("click", function () {
                if ($('#fileToUpload').val() == "") {
                    $("#spanfile").html("Please upload file");
                    return false;
                }
                else {
                    return checkfile();
                }
            });

            function checkfile() {
                var file = getNameFromPath($("#fileToUpload").val());
                if (file != null) {
                    var extension = file.substr((file.lastIndexOf('.') + 1));
                    // alert(extension);
                    switch (extension) {
                        case 'txt':
                            flag = true;
                            break;
                        default:
                            flag = false;
                    }
                }
                if (flag == false) {
                    $("#spanfile").text("You can upload only txt extension file");
                    return false;
                }
                else {
                    var size = GetFileSize('fileToUpload');
                    if (size > 3) {
                        $("#spanfile").text("You can upload file up to 3 MB");
                        return false;
                    }
                    else {
                        $("#spanfile").text("");
                    }
                }
            }

            $(function () {
                $("#fileToUpload").change(function () {
                    checkfile();
                });
            });
        </script>

Lexikar/Views/Deprecated/Upload.cshtml
@{
    ViewBag.Title = "Nahrávání všech souborů";
}

<div class="row">
    <div class="well well-lg" style="background-color: lightgray">
        <div class="well">
            <h2>FileUpload</h2>
            <h3>@ViewBag.Message</h3>
            @using (Html.BeginForm("Upload", "Translation", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.ValidationSummary();
                <ul>
                    <li class="lifile">
                        <input type="file" id="fileToUpload" name="Lex" />
                        <label></label>
                        <span class="field-validation-error" id="spanfile"></span>
                    </li>
                    <li>
                        <input type="file" id="fileToUpload" name="Corpus" />
                        <span class="field-validation-error" id="spanfile"></span>
                    </li>
                    <li>
                        <input type="file" id="fileToUpload" name="Help" />
                        <span class="field-validation-error" id="spanfile"></span>
                    </li>
                    <li>
                        <input type="file" id="fileToUpload" name="About" />
                        <span class="field-validation-error" id="spanfile"></span>
                    </li>
                </ul>
                <input type="submit" id="btnSubmit" value="Upload" />
            }
        </div>
    </div>
</div>